version: "3.9"

services:
  leolani:
    image: "piekvossen/leolani-text-to-ekg"
    ports:
      - "8000:8000"
    volumes:
      - ./config:/leolani-text-to-ekg/app/py-app/config    
      - ./storage:/leolani-text-to-ekg/app/py-app/storage
      - ./resources:/leolani-text-to-ekg/app/py-app/resources
